---

- name: FILEBEAT ON REDHAT | Add repository
  yum_repository:
    name: filebeat
    description: Elastic repository for 6.x packages
    baseurl: "{{ filebeat_yum_repository }}"
    gpgcheck: yes
    gpgkey: "{{ filebeat_yum_key }}"
